import { HouseNumber, Interpretation, PlanetKey } from '../types'

export type PlanetHouseLexicon = Partial<
  Record<PlanetKey, Partial<Record<HouseNumber, Interpretation>>>
>

export const PLANET_HOUSE_MEANINGS: PlanetHouseLexicon = {
  Sun: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Moon: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Mercury: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Venus: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Mars: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Jupiter: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Saturn: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Uranus: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Neptune: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },

  Pluto: {
    1: { short: '', long: `` },
    2: { short: '', long: `` },
    3: { short: '', long: `` },
    4: { short: '', long: `` },
    5: { short: '', long: `` },
    6: { short: '', long: `` },
    7: { short: '', long: `` },
    8: { short: '', long: `` },
    9: { short: '', long: `` },
    10: { short: '', long: `` },
    11: { short: '', long: `` },
    12: { short: '', long: `` },
  },
}