import type { HouseNumber } from '../types'
import type { HouseGuidance } from './types'

export const HOUSE_GUIDANCE: Record<HouseNumber, HouseGuidance> = {
  1: {
    id: 'guidance.house.1',
    category: 'house',
    house: 1,
    tone: 'intensifying',
    intensity: 'high',
    tags: ['identity', 'confidence', 'action', 'awareness'],
    focus: 'identity, presence, and how you initiate',
    constructive: 'Choose how you want to show up before responding automatically.',
    watchFor: 'Immediate reactions may be mistaken for the whole truth of the moment.',
    inquiry: 'What response would feel both authentic and intentional?',
  },
  2: {
    id: 'guidance.house.2',
    category: 'house',
    house: 2,
    tone: 'integrative',
    intensity: 'medium',
    tags: ['values', 'resources', 'security', 'self-worth'],
    focus: 'values, resources, self-worth, and stability',
    constructive: 'Support what is genuinely valuable with a practical choice.',
    watchFor: 'Scarcity or comparison may distort what enough looks like.',
    inquiry: 'What deserves your time, energy, or resources today?',
  },
  3: {
    id: 'guidance.house.3',
    category: 'house',
    house: 3,
    tone: 'integrative',
    intensity: 'medium',
    tags: ['communication', 'learning', 'decisions', 'awareness'],
    focus: 'communication, learning, and everyday thinking',
    constructive: 'Make the next conversation or piece of information clear and useful.',
    watchFor: 'Noise, assumptions, or repetition may distract from the real message.',
    inquiry: 'What needs to be understood or expressed more simply?',
  },
  4: {
    id: 'guidance.house.4',
    category: 'house',
    house: 4,
    tone: 'integrative',
    intensity: 'high',
    tags: ['home', 'emotions', 'security', 'rest'],
    focus: 'home, roots, privacy, and emotional foundation',
    constructive: 'Create a small pocket of safety before addressing outer demands.',
    watchFor: 'Protectiveness may become withdrawal or repeating an old family pattern.',
    inquiry: 'What would help you feel grounded without avoiding what matters?',
  },
  5: {
    id: 'guidance.house.5',
    category: 'house',
    house: 5,
    tone: 'supportive',
    intensity: 'medium',
    tags: ['creativity', 'confidence', 'relationships', 'gratitude'],
    focus: 'creativity, pleasure, romance, and self-expression',
    constructive: 'Give genuine enjoyment or creative curiosity a little room to lead.',
    watchFor: 'The desire for attention may overshadow the pleasure of the activity itself.',
    inquiry: 'What would you create or enjoy without needing it to impress anyone?',
  },
  6: {
    id: 'guidance.house.6',
    category: 'house',
    house: 6,
    tone: 'integrative',
    intensity: 'medium',
    tags: ['routines', 'work', 'structure', 'focus'],
    focus: 'daily routines, responsibilities, service, and practical upkeep',
    constructive: 'Improve one repeatable habit instead of trying to optimize everything.',
    watchFor: 'Productivity pressure may turn a useful routine into self-judgment.',
    inquiry: 'Which small routine would make the day easier to carry?',
  },
  7: {
    id: 'guidance.house.7',
    category: 'house',
    house: 7,
    tone: 'integrative',
    intensity: 'high',
    tags: ['relationships', 'communication', 'boundaries', 'values'],
    focus: 'partnership, reciprocity, and one-to-one dynamics',
    constructive: 'Make room for both perspectives without abandoning your own position.',
    watchFor: 'Projection or peacekeeping may hide the boundary that needs attention.',
    inquiry: 'What would mutual respect look like in this exchange?',
  },
  8: {
    id: 'guidance.house.8',
    category: 'house',
    house: 8,
    tone: 'intensifying',
    intensity: 'high',
    tags: ['transformation', 'power', 'resources', 'boundaries'],
    focus: 'shared resources, trust, vulnerability, and transformation',
    constructive: 'Approach the deeper issue with honesty, pacing, and clear consent.',
    watchFor: 'Intensity may encourage control, secrecy, or an all-or-nothing response.',
    inquiry: 'What can be shared, clarified, or released without forcing the outcome?',
  },
  9: {
    id: 'guidance.house.9',
    category: 'house',
    house: 9,
    tone: 'supportive',
    intensity: 'medium',
    tags: ['learning', 'growth', 'perspective', 'beliefs'],
    focus: 'beliefs, perspective, higher learning, and exploration',
    constructive: 'Let a wider perspective inform one grounded choice.',
    watchFor: 'A compelling belief may be treated as complete before it is tested.',
    inquiry: 'What might become possible if you examined this from another viewpoint?',
  },
  10: {
    id: 'guidance.house.10',
    category: 'house',
    house: 10,
    tone: 'intensifying',
    intensity: 'high',
    tags: ['work', 'responsibility', 'confidence', 'structure'],
    focus: 'vocation, visibility, responsibility, and long-term direction',
    constructive: 'Choose the next visible action that matches the reputation you want to build.',
    watchFor: 'External expectations may define success more loudly than your own values.',
    inquiry: 'What kind of contribution would feel both useful and true to you?',
  },
  11: {
    id: 'guidance.house.11',
    category: 'house',
    house: 11,
    tone: 'supportive',
    intensity: 'medium',
    tags: ['community', 'relationships', 'growth', 'perspective'],
    focus: 'community, friendship, collaboration, and future goals',
    constructive: 'Connect one personal goal to a useful shared effort.',
    watchFor: 'Group expectations may blur your own priorities or limits.',
    inquiry: 'Where could participation create more possibility than working alone?',
  },
  12: {
    id: 'guidance.house.12',
    category: 'house',
    house: 12,
    tone: 'integrative',
    intensity: 'medium',
    tags: ['rest', 'imagination', 'compassion', 'awareness', 'grounding'],
    focus: 'rest, reflection, endings, and the less visible inner world',
    constructive: 'Create quiet space to notice what needs rest, release, or compassion.',
    watchFor: 'Avoidance or blurred boundaries may be mistaken for surrender.',
    inquiry: 'What can you gently set down so there is room to listen?',
  },
}

export function getHouseGuidance(house: HouseNumber): HouseGuidance {
  return HOUSE_GUIDANCE[house]
}
