import {
  hasAnyGuidanceTag,
  type GuidanceTag,
  type SuggestedPractice,
} from './types'

export const SUGGESTED_PRACTICES = [
  {
    id: 'guidance.practice.sensory-grounding',
    category: 'practice',
    practiceCategory: 'grounding',
    tone: 'integrative',
    intensity: 'low',
    tags: ['grounding', 'awareness', 'emotions', 'rest'],
    title: 'Five-sense grounding',
    summary: 'Pause and reconnect with the immediate environment.',
    steps: [
      'Notice one thing you can see, hear, feel, smell, and taste.',
      'Name the next small action you want to take.',
    ],
    durationMinutes: 3,
    sourceIds: ['guidance.transit.moon', 'guidance.sign.taurus'],
  },
  {
    id: 'guidance.practice.pause-before-responding',
    category: 'practice',
    practiceCategory: 'relationships',
    tone: 'integrative',
    intensity: 'low',
    tags: ['communication', 'relationships', 'boundaries', 'awareness'],
    title: 'Pause before responding',
    summary: 'Create a brief space between the first reaction and the reply.',
    steps: [
      'Read or hear the message once without composing a response.',
      'Write the essential point you want to communicate, then respond simply.',
    ],
    durationMinutes: 5,
    sourceIds: ['guidance.transit.mercury', 'guidance.aspect.opp'],
  },
  {
    id: 'guidance.practice.single-task-reset',
    category: 'practice',
    practiceCategory: 'focus',
    tone: 'supportive',
    intensity: 'low',
    tags: ['focus', 'structure', 'work', 'routines'],
    title: 'Single-task reset',
    summary: 'Reduce noise by completing one bounded task.',
    steps: [
      'Choose one task that can be advanced in fifteen minutes.',
      'Silence avoidable distractions and work only on that task.',
    ],
    durationMinutes: 15,
    sourceIds: ['guidance.transit.sun', 'guidance.house.6'],
  },
  {
    id: 'guidance.practice.short-walk',
    category: 'practice',
    practiceCategory: 'movement',
    tone: 'supportive',
    intensity: 'low',
    tags: ['action', 'grounding', 'perspective', 'rest'],
    title: 'Short walk and reset',
    summary: 'Use gentle movement to create space around a busy moment.',
    steps: [
      'Take a comfortable walk at an easy pace.',
      'Return with one sentence describing what feels clearer.',
    ],
    durationMinutes: 10,
    sourceIds: ['guidance.transit.mars', 'guidance.sign.sagittarius'],
  },
  {
    id: 'guidance.practice.values-check',
    category: 'practice',
    practiceCategory: 'journaling',
    tone: 'integrative',
    intensity: 'low',
    tags: ['values', 'decisions', 'resources', 'self-worth'],
    title: 'Three-value check',
    summary: 'Compare a choice with the values you want it to express.',
    steps: [
      'Write three values that matter in this decision.',
      'Note which available option best respects those values and why.',
    ],
    durationMinutes: 8,
    sourceIds: ['guidance.transit.venus', 'guidance.house.2'],
  },
  {
    id: 'guidance.practice.boundary-review',
    category: 'practice',
    practiceCategory: 'relationships',
    tone: 'challenging',
    intensity: 'low',
    tags: ['boundaries', 'relationships', 'communication', 'power'],
    title: 'Boundary review',
    summary: 'Turn a vague discomfort into a respectful, specific limit.',
    steps: [
      'Name the behavior or request that needs clarity.',
      'Draft one calm sentence stating what you can or cannot do.',
    ],
    durationMinutes: 8,
    sourceIds: ['guidance.target.mars', 'guidance.house.7'],
  },
  {
    id: 'guidance.practice.gratitude-list',
    category: 'practice',
    practiceCategory: 'gratitude',
    tone: 'supportive',
    intensity: 'low',
    tags: ['gratitude', 'values', 'relationships', 'resources'],
    title: 'Specific gratitude list',
    summary: 'Notice support that is already present without denying difficulty.',
    steps: [
      'Write three specific things you appreciate today.',
      'Choose one small way to acknowledge or care for one of them.',
    ],
    durationMinutes: 5,
    sourceIds: ['guidance.transit.venus', 'guidance.aspect.trine'],
  },
  {
    id: 'guidance.practice.creative-free-write',
    category: 'practice',
    practiceCategory: 'creativity',
    tone: 'supportive',
    intensity: 'low',
    tags: ['creativity', 'imagination', 'identity', 'awareness'],
    title: 'Creative free-write',
    summary: 'Let an idea move without editing it into usefulness too soon.',
    steps: [
      'Set a short timer and write continuously from the prompt: I keep noticing...',
      'Underline one sentence that feels alive or surprising.',
    ],
    durationMinutes: 10,
    sourceIds: ['guidance.house.5', 'guidance.target.neptune'],
  },
  {
    id: 'guidance.practice.tidy-one-area',
    category: 'practice',
    practiceCategory: 'grounding',
    tone: 'integrative',
    intensity: 'low',
    tags: ['grounding', 'structure', 'home', 'routines'],
    title: 'Tidy one small area',
    summary: 'Create visible order without turning the whole day into a project.',
    steps: [
      'Choose one surface, drawer, or digital folder.',
      'Stop when that defined area is usable, even if more remains elsewhere.',
    ],
    durationMinutes: 10,
    sourceIds: ['guidance.sign.virgo', 'guidance.house.4'],
  },
  {
    id: 'guidance.practice.reciprocity-check-in',
    category: 'practice',
    practiceCategory: 'relationships',
    tone: 'integrative',
    intensity: 'low',
    tags: ['relationships', 'communication', 'values', 'boundaries'],
    title: 'Reciprocity check-in',
    summary: 'Notice what is being given, received, and left unsaid.',
    steps: [
      'Write what you are offering and what you are asking for.',
      'Choose one respectful conversation or boundary that would add clarity.',
    ],
    durationMinutes: 8,
    sourceIds: ['guidance.sign.libra', 'guidance.target.venus'],
  },
  {
    id: 'guidance.practice.rest-window',
    category: 'practice',
    practiceCategory: 'grounding',
    tone: 'integrative',
    intensity: 'low',
    tags: ['rest', 'grounding', 'compassion', 'awareness'],
    title: 'Protected rest window',
    summary: 'Set aside a short period with no requirement to produce or solve.',
    steps: [
      'Choose a brief window and silence avoidable demands.',
      'Rest quietly or do one gentle activity that feels restorative.',
    ],
    durationMinutes: 15,
    sourceIds: ['guidance.house.12', 'guidance.sign.pisces'],
  },
  {
    id: 'guidance.practice.decision-notes',
    category: 'practice',
    practiceCategory: 'journaling',
    tone: 'integrative',
    intensity: 'low',
    tags: ['decisions', 'communication', 'perspective', 'focus'],
    title: 'Decision notes',
    summary: 'Separate facts, preferences, and unknowns before choosing.',
    steps: [
      'Make three short lists: facts, preferences, and unknowns.',
      'Identify the next decision that can be made with the information available.',
    ],
    durationMinutes: 10,
    sourceIds: ['guidance.transit.mercury', 'guidance.aspect.sextile'],
  },
  {
    id: 'guidance.practice.three-line-check-in',
    category: 'practice',
    practiceCategory: 'journaling',
    tone: 'integrative',
    intensity: 'low',
    tags: ['emotions', 'awareness', 'grounding', 'decisions'],
    title: 'Three-line check-in',
    summary: 'Name the feeling, the need, and the response you want to choose.',
    steps: [
      'Write one line each for: I feel, I need, and I choose.',
      'Keep the chosen response small enough to act on today.',
    ],
    durationMinutes: 5,
    sourceIds: ['guidance.transit.moon', 'guidance.target.moon'],
  },
  {
    id: 'guidance.practice.intentional-pause',
    category: 'practice',
    practiceCategory: 'grounding',
    tone: 'challenging',
    intensity: 'low',
    tags: ['awareness', 'action', 'grounding', 'boundaries'],
    title: 'Two-minute pause',
    summary: 'Let the first wave of urgency pass before choosing a response.',
    steps: [
      'Step away from the message or task for two minutes if it is safe to do so.',
      'Return and name the result you want before acting.',
    ],
    durationMinutes: 2,
    sourceIds: ['guidance.transit.mars', 'guidance.aspect.square'],
  },
  {
    id: 'guidance.practice.priority-trim',
    category: 'practice',
    practiceCategory: 'focus',
    tone: 'challenging',
    intensity: 'low',
    tags: ['focus', 'responsibility', 'work', 'structure'],
    title: 'Trim the priority list',
    summary: 'Reduce competing demands to one essential task and one optional task.',
    steps: [
      'Mark each current task as essential, optional, or not for today.',
      'Begin the smallest useful step on the essential task.',
    ],
    durationMinutes: 7,
    sourceIds: ['guidance.transit.sun', 'guidance.transit.saturn'],
  },
  {
    id: 'guidance.practice.conversation-outline',
    category: 'practice',
    practiceCategory: 'relationships',
    tone: 'integrative',
    intensity: 'low',
    tags: ['communication', 'relationships', 'boundaries', 'decisions'],
    title: 'Conversation outline',
    summary: 'Prepare a direct conversation without scripting the other person.',
    steps: [
      'Write one observation, one request, and one question you genuinely want answered.',
      'Remove accusations, predictions, and points that do not serve the main purpose.',
    ],
    durationMinutes: 8,
    sourceIds: ['guidance.transit.mercury', 'guidance.target.venus'],
  },
  {
    id: 'guidance.practice.capacity-inventory',
    category: 'practice',
    practiceCategory: 'journaling',
    tone: 'challenging',
    intensity: 'low',
    tags: ['boundaries', 'responsibility', 'resources', 'relationships'],
    title: 'Capacity inventory',
    summary: 'Check available time and effort before adding another commitment.',
    steps: [
      'List the commitments that already require your attention this week.',
      'Decide whether the new request receives a yes, no, or a smaller counteroffer.',
    ],
    durationMinutes: 8,
    sourceIds: ['guidance.transit.saturn', 'guidance.target.venus'],
  },
  {
    id: 'guidance.practice.assumption-audit',
    category: 'practice',
    practiceCategory: 'journaling',
    tone: 'integrative',
    intensity: 'low',
    tags: ['awareness', 'communication', 'perspective', 'decisions'],
    title: 'Assumption audit',
    summary: 'Separate what happened from the meaning you assigned to it.',
    steps: [
      'Write two columns labeled observed and inferred.',
      'Choose one inference to verify with a question or additional information.',
    ],
    durationMinutes: 7,
    sourceIds: ['guidance.transit.mercury', 'guidance.target.neptune'],
  },
  {
    id: 'guidance.practice.quiet-input-window',
    category: 'practice',
    practiceCategory: 'grounding',
    tone: 'integrative',
    intensity: 'low',
    tags: ['focus', 'rest', 'awareness', 'communication'],
    title: 'Quiet the inputs',
    summary: 'Reduce optional stimulation long enough to hear your own priority.',
    steps: [
      'Silence notifications and pause optional media for ten minutes.',
      'Use the quieter window for one task, decision, or genuine rest.',
    ],
    durationMinutes: 10,
    sourceIds: ['guidance.transit.mercury', 'guidance.sign.aquarius'],
  },
  {
    id: 'guidance.practice.perspective-swap',
    category: 'practice',
    practiceCategory: 'relationships',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['relationships', 'perspective', 'communication', 'integration'],
    title: 'Three-view perspective',
    summary: 'Look at a disagreement from your view, their possible view, and shared facts.',
    steps: [
      'State your view without argument or exaggeration.',
      'Write one plausible alternative view, then list what both sides can verify.',
    ],
    durationMinutes: 8,
    sourceIds: ['guidance.aspect.opp', 'guidance.transit.jupiter'],
  },
  {
    id: 'guidance.practice.completion-pass',
    category: 'practice',
    practiceCategory: 'focus',
    tone: 'supportive',
    intensity: 'low',
    tags: ['action', 'focus', 'structure', 'work'],
    title: 'Completion pass',
    summary: 'Finish one nearly complete task before opening another loop.',
    steps: [
      'Choose a useful task that is already close to done.',
      'Complete, send, file, or schedule it before starting something new.',
    ],
    durationMinutes: 10,
    sourceIds: ['guidance.transit.mars', 'guidance.target.saturn'],
  },
  {
    id: 'guidance.practice.appreciation-message',
    category: 'practice',
    practiceCategory: 'gratitude',
    tone: 'supportive',
    intensity: 'low',
    tags: ['gratitude', 'relationships', 'communication', 'values'],
    title: 'Specific appreciation',
    summary: 'Turn appreciation into a clear acknowledgment someone can receive.',
    steps: [
      'Choose one person and name the specific action or quality you appreciate.',
      'Share it simply, without attaching a request or minimizing the message.',
    ],
    durationMinutes: 5,
    sourceIds: ['guidance.transit.venus', 'guidance.target.sun'],
  },
  {
    id: 'guidance.practice.one-variable-experiment',
    category: 'practice',
    practiceCategory: 'creativity',
    tone: 'intensifying',
    intensity: 'low',
    tags: ['change', 'freedom', 'creativity', 'routines'],
    title: 'One-variable experiment',
    summary: 'Change one part of a familiar process and test the alternative once.',
    steps: [
      'Choose a low-stakes routine or task and change its order, location, tool, or route.',
      'Try the alternative once and keep only what makes the process more useful.',
    ],
    durationMinutes: 10,
    sourceIds: ['guidance.target.uranus'],
  },
  {
    id: 'guidance.practice.release-one-control',
    category: 'practice',
    practiceCategory: 'focus',
    tone: 'intensifying',
    intensity: 'low',
    tags: ['power', 'transformation', 'boundaries', 'awareness'],
    title: 'Release one point of control',
    summary: 'Loosen your grip on one low-stakes detail that does not require managing.',
    steps: [
      'Choose one outcome you are overmanaging and define the part that is actually yours.',
      'Delegate, defer, or leave one nonessential detail alone for the rest of the day.',
    ],
    durationMinutes: 5,
    sourceIds: ['guidance.target.pluto'],
  },
] as const satisfies readonly SuggestedPractice[]

export function getSuggestedPractice(id: string): SuggestedPractice | null {
  return SUGGESTED_PRACTICES.find((practice) => practice.id === id) ?? null
}

export function findSuggestedPracticesByTags(
  tags: readonly GuidanceTag[]
): SuggestedPractice[] {
  return SUGGESTED_PRACTICES.filter((practice) =>
    hasAnyGuidanceTag(practice.tags, tags)
  )
}
