import {
  hasAnyGuidanceTag,
  type GuidanceTag,
  type ReflectionPrompt,
} from './types'

export const REFLECTION_PROMPTS = [
  {
    id: 'guidance.prompt.emotional-need',
    category: 'reflection-prompt',
    promptCategory: 'awareness',
    tone: 'integrative',
    intensity: 'low',
    tags: ['emotions', 'security', 'awareness'],
    title: 'Name the need',
    prompt: 'What feeling is most present, and what reasonable need may sit beneath it?',
    followUp: 'What is one kind response that supports the need without acting on every impulse?',
    sourceIds: ['guidance.transit.moon', 'guidance.target.moon'],
  },
  {
    id: 'guidance.prompt.intentional-presence',
    category: 'reflection-prompt',
    promptCategory: 'integration',
    tone: 'supportive',
    intensity: 'low',
    tags: ['identity', 'confidence', 'focus'],
    title: 'Choose your presence',
    prompt: 'How do you want to show up in the situation that has most of your attention?',
    followUp: 'Which single action would make that intention visible?',
    sourceIds: ['guidance.transit.sun', 'guidance.target.sun'],
  },
  {
    id: 'guidance.prompt.clear-message',
    category: 'reflection-prompt',
    promptCategory: 'awareness',
    tone: 'integrative',
    intensity: 'low',
    tags: ['communication', 'decisions', 'focus'],
    title: 'Clarify the message',
    prompt: 'What do you know, what are you assuming, and what still needs to be asked?',
    followUp: 'How could you express the essential point in one clear sentence?',
    sourceIds: ['guidance.transit.mercury', 'guidance.target.mercury'],
  },
  {
    id: 'guidance.prompt.values-alignment',
    category: 'reflection-prompt',
    promptCategory: 'values',
    tone: 'supportive',
    intensity: 'low',
    tags: ['values', 'relationships', 'self-worth'],
    title: 'Check the value beneath the choice',
    prompt: 'Which value do you want this choice or relationship to reflect?',
    followUp: 'What would alignment look like without seeking approval?',
    sourceIds: ['guidance.transit.venus', 'guidance.target.venus'],
  },
  {
    id: 'guidance.prompt.directed-action',
    category: 'reflection-prompt',
    promptCategory: 'action',
    tone: 'intensifying',
    intensity: 'low',
    tags: ['action', 'boundaries', 'focus'],
    title: 'Direct the energy',
    prompt: 'What action is actually needed, and what reaction can be allowed to pass?',
    followUp: 'What is the smallest direct step that respects your boundaries?',
    sourceIds: ['guidance.transit.mars', 'guidance.target.mars'],
  },
  {
    id: 'guidance.prompt.grounded-growth',
    category: 'reflection-prompt',
    promptCategory: 'integration',
    tone: 'supportive',
    intensity: 'low',
    tags: ['growth', 'learning', 'perspective'],
    title: 'Expand with proportion',
    prompt: 'Which possibility feels meaningful enough to explore without overcommitting?',
    followUp: 'What practical limit would help that growth remain sustainable?',
    sourceIds: ['guidance.transit.jupiter', 'guidance.target.jupiter'],
  },
  {
    id: 'guidance.prompt.sustainable-structure',
    category: 'reflection-prompt',
    promptCategory: 'action',
    tone: 'challenging',
    intensity: 'low',
    tags: ['responsibility', 'structure', 'work'],
    title: 'Build the next support',
    prompt: 'Which responsibility needs a clearer structure rather than more pressure?',
    followUp: 'What repeatable next step would make progress easier to sustain?',
    sourceIds: ['guidance.transit.saturn', 'guidance.target.saturn'],
  },
  {
    id: 'guidance.prompt.balance-polarity',
    category: 'reflection-prompt',
    promptCategory: 'boundaries',
    tone: 'integrative',
    intensity: 'high',
    tags: ['relationships', 'boundaries', 'perspective'],
    title: 'Hold both sides',
    prompt: 'Which two needs seem opposed, and what is each one trying to protect?',
    followUp: 'What boundary or agreement could respect both without forcing a false compromise?',
    sourceIds: ['guidance.aspect.opp', 'guidance.house.7'],
  },
  {
    id: 'guidance.prompt.friction-adjustment',
    category: 'reflection-prompt',
    promptCategory: 'action',
    tone: 'challenging',
    intensity: 'high',
    tags: ['change', 'action', 'growth'],
    title: 'Use the friction',
    prompt: 'What recurring point of friction is asking for an adjustment rather than more force?',
    followUp: 'Which skill, limit, or expectation could be changed first?',
    sourceIds: ['guidance.aspect.square'],
  },
  {
    id: 'guidance.prompt.use-the-ease',
    category: 'reflection-prompt',
    promptCategory: 'action',
    tone: 'supportive',
    intensity: 'low',
    tags: ['growth', 'confidence', 'creativity'],
    title: 'Participate in what is flowing',
    prompt: 'What feels naturally available now but still needs your participation?',
    followUp: 'How can you use that ease in a way that creates lasting value?',
    sourceIds: ['guidance.aspect.trine'],
  },
  {
    id: 'guidance.prompt.quiet-opening',
    category: 'reflection-prompt',
    promptCategory: 'awareness',
    tone: 'supportive',
    intensity: 'low',
    tags: ['awareness', 'learning', 'communication'],
    title: 'Notice the opening',
    prompt: 'What useful option is available even though it is not demanding your attention?',
    followUp: 'What modest action would help you engage it?',
    sourceIds: ['guidance.aspect.sextile'],
  },
  {
    id: 'guidance.prompt.intensity-choice',
    category: 'reflection-prompt',
    promptCategory: 'integration',
    tone: 'intensifying',
    intensity: 'high',
    tags: ['focus', 'awareness', 'integration'],
    title: 'Work with the concentration',
    prompt: 'What has become louder or more concentrated, and what deserves your attention within it?',
    followUp: 'How can you stay intentional without letting one theme take over?',
    sourceIds: ['guidance.aspect.conj'],
  },
  {
    id: 'guidance.prompt.resource-stewardship',
    category: 'reflection-prompt',
    promptCategory: 'values',
    tone: 'integrative',
    intensity: 'low',
    tags: ['resources', 'values', 'self-worth'],
    title: 'Choose what to support',
    prompt: 'Where are your time, attention, or resources going, and does that reflect your values?',
    sourceIds: ['guidance.house.2'],
  },
  {
    id: 'guidance.prompt.inner-foundation',
    category: 'reflection-prompt',
    promptCategory: 'awareness',
    tone: 'integrative',
    intensity: 'low',
    tags: ['home', 'security', 'emotions'],
    title: 'Support the foundation',
    prompt: 'What would make your inner or physical space feel a little more supportive today?',
    sourceIds: ['guidance.house.4'],
  },
  {
    id: 'guidance.prompt.create-without-performance',
    category: 'reflection-prompt',
    promptCategory: 'action',
    tone: 'supportive',
    intensity: 'low',
    tags: ['creativity', 'confidence', 'gratitude'],
    title: 'Create for the experience',
    prompt: 'What would you enjoy making or expressing if no one needed to approve it?',
    sourceIds: ['guidance.house.5'],
  },
  {
    id: 'guidance.prompt.shared-future',
    category: 'reflection-prompt',
    promptCategory: 'integration',
    tone: 'supportive',
    intensity: 'low',
    tags: ['community', 'growth', 'relationships'],
    title: 'Connect purpose with community',
    prompt: 'Which future goal could benefit from collaboration or a shared perspective?',
    sourceIds: ['guidance.house.11'],
  },
  {
    id: 'guidance.prompt.gentle-release',
    category: 'reflection-prompt',
    promptCategory: 'integration',
    tone: 'integrative',
    intensity: 'low',
    tags: ['rest', 'compassion', 'grounding'],
    title: 'Make room to listen',
    prompt: 'What can be paused or set down long enough for you to hear what you need?',
    sourceIds: ['guidance.house.12'],
  },
  {
    id: 'guidance.prompt.flexible-change',
    category: 'reflection-prompt',
    promptCategory: 'action',
    tone: 'intensifying',
    intensity: 'high',
    tags: ['change', 'freedom', 'awareness'],
    title: 'Change one variable',
    prompt: 'Where would a flexible experiment serve you better than either staying stuck or changing everything?',
    sourceIds: ['guidance.target.uranus'],
  },
  {
    id: 'guidance.prompt.ground-the-vision',
    category: 'reflection-prompt',
    promptCategory: 'integration',
    tone: 'integrative',
    intensity: 'low',
    tags: ['imagination', 'creativity', 'grounding'],
    title: 'Give the vision a form',
    prompt: 'What intuition or idea could be tested through one small concrete action?',
    sourceIds: ['guidance.target.neptune'],
  },
  {
    id: 'guidance.prompt.power-and-choice',
    category: 'reflection-prompt',
    promptCategory: 'boundaries',
    tone: 'intensifying',
    intensity: 'high',
    tags: ['power', 'transformation', 'boundaries'],
    title: 'Return to your choice',
    prompt: 'What is within your influence, and what are you trying to control beyond it?',
    followUp: 'What would a clear, proportionate choice look like now?',
    sourceIds: ['guidance.target.pluto'],
  },
] as const satisfies readonly ReflectionPrompt[]

export function getReflectionPrompt(id: string): ReflectionPrompt | null {
  return REFLECTION_PROMPTS.find((prompt) => prompt.id === id) ?? null
}

export function findReflectionPromptsByTags(
  tags: readonly GuidanceTag[]
): ReflectionPrompt[] {
  return REFLECTION_PROMPTS.filter((prompt) =>
    hasAnyGuidanceTag(prompt.tags, tags)
  )
}
