import type { ZodiacName } from '../types'
import type { SignGuidance } from './types'

export const SIGN_GUIDANCE: Record<ZodiacName, SignGuidance> = {
  Aries: {
    id: 'guidance.sign.aries',
    category: 'sign',
    sign: 'Aries',
    tone: 'intensifying',
    intensity: 'high',
    tags: ['action', 'confidence', 'focus', 'boundaries'],
    atmosphere: 'Direct, active, and ready to move.',
    constructive: 'Choose a clear first step and leave room to adjust.',
    watchFor: 'Urgency may become impatience or a reaction before reflection.',
    opportunity: 'Use courage to begin something that has needed momentum.',
  },
  Taurus: {
    id: 'guidance.sign.taurus',
    category: 'sign',
    sign: 'Taurus',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['grounding', 'security', 'resources', 'values', 'rest'],
    atmosphere: 'Steady, sensory, and oriented toward what is sustainable.',
    constructive: 'Slow down enough to notice what genuinely supports stability.',
    watchFor: 'Comfort may become resistance when a small change would help.',
    opportunity: 'Strengthen one resource, routine, or value through consistent care.',
  },
  Gemini: {
    id: 'guidance.sign.gemini',
    category: 'sign',
    sign: 'Gemini',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['communication', 'learning', 'decisions', 'awareness'],
    atmosphere: 'Mentally mobile, conversational, and alert to alternatives.',
    constructive: 'Compare interpretations, then organize the useful information before moving on.',
    watchFor: 'Collecting one more input may postpone a choice that is ready to be made.',
    opportunity: 'Translate a complicated idea into language someone else can use.',
  },
  Cancer: {
    id: 'guidance.sign.cancer',
    category: 'sign',
    sign: 'Cancer',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['emotions', 'home', 'security', 'compassion', 'boundaries'],
    atmosphere: 'Sensitive, protective, and attentive to belonging.',
    constructive: 'Acknowledge the feeling and support the need beneath it.',
    watchFor: 'Self-protection may become withdrawal or taking everything personally.',
    opportunity: 'Create a little more safety through care, honesty, or a clear boundary.',
  },
  Leo: {
    id: 'guidance.sign.leo',
    category: 'sign',
    sign: 'Leo',
    tone: 'supportive',
    intensity: 'high',
    tags: ['confidence', 'creativity', 'identity', 'gratitude'],
    atmosphere: 'Expressive, warm, and ready to be seen.',
    constructive: 'Share what is sincere rather than performing for a response.',
    watchFor: 'Pride or the need for recognition may make feedback harder to hear.',
    opportunity: 'Lead with generosity and give a creative idea visible form.',
  },
  Virgo: {
    id: 'guidance.sign.virgo',
    category: 'sign',
    sign: 'Virgo',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['focus', 'routines', 'work', 'awareness', 'structure'],
    atmosphere: 'Observant, practical, and ready to refine what is not working.',
    constructive: 'Improve one useful detail while accepting that progress can be imperfect.',
    watchFor: 'Discernment may turn into overanalysis or unnecessary self-criticism.',
    opportunity: 'Simplify a process, routine, or decision so it serves its purpose better.',
  },
  Libra: {
    id: 'guidance.sign.libra',
    category: 'sign',
    sign: 'Libra',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['relationships', 'values', 'communication', 'boundaries'],
    atmosphere: 'Attuned to proportion, reciprocity, and the effect of choices on others.',
    constructive: 'Include your own preference while listening for what fair exchange requires.',
    watchFor: 'Polishing the conversation may delay the decision or boundary underneath it.',
    opportunity: 'Clarify an agreement so cooperation depends less on unspoken expectations.',
  },
  Scorpio: {
    id: 'guidance.sign.scorpio',
    category: 'sign',
    sign: 'Scorpio',
    tone: 'intensifying',
    intensity: 'high',
    tags: ['emotions', 'power', 'boundaries', 'transformation', 'awareness'],
    atmosphere: 'Focused, private, and drawn toward what lies beneath the surface.',
    constructive: 'Name the deeper concern without trying to control every outcome.',
    watchFor: 'Suspicion or all-or-nothing thinking may amplify an uncertain situation.',
    opportunity: 'Release one stale pattern and choose a more honest form of engagement.',
  },
  Sagittarius: {
    id: 'guidance.sign.sagittarius',
    category: 'sign',
    sign: 'Sagittarius',
    tone: 'supportive',
    intensity: 'medium',
    tags: ['growth', 'learning', 'perspective', 'beliefs', 'freedom'],
    atmosphere: 'Restless for context, candid in expression, and drawn toward a wider horizon.',
    constructive: 'Test a belief against experience while keeping the relevant details in view.',
    watchFor: 'A compelling explanation may become certainty before it has been tested.',
    opportunity: 'Ask the larger question, seek informed perspective, or explore unfamiliar ground.',
  },
  Capricorn: {
    id: 'guidance.sign.capricorn',
    category: 'sign',
    sign: 'Capricorn',
    tone: 'challenging',
    intensity: 'high',
    tags: ['responsibility', 'structure', 'work', 'focus', 'boundaries'],
    atmosphere: 'Measured, goal-conscious, and attentive to consequence and durability.',
    constructive: 'Distinguish the essential duty from inherited pressure, then work the next step.',
    watchFor: 'Competence may become overcontrol or an assumption that support must be earned first.',
    opportunity: 'Set a standard or schedule that can support the goal beyond the current push.',
  },
  Aquarius: {
    id: 'guidance.sign.aquarius',
    category: 'sign',
    sign: 'Aquarius',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['change', 'community', 'freedom', 'perspective', 'awareness'],
    atmosphere: 'Independent, future-oriented, and open to an unconventional view.',
    constructive: 'Experiment with a new approach while staying connected to real needs.',
    watchFor: 'Distance or contrarian thinking may replace emotional presence.',
    opportunity: 'Improve a system or contribute an original idea to a shared problem.',
  },
  Pisces: {
    id: 'guidance.sign.pisces',
    category: 'sign',
    sign: 'Pisces',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['imagination', 'compassion', 'creativity', 'rest', 'grounding'],
    atmosphere: 'Receptive, imaginative, and responsive to subtle impressions and shared moods.',
    constructive: 'Translate an impression into art, rest, a question, or another observable form.',
    watchFor: 'Absorbing the surrounding mood may blur which priority or feeling is actually yours.',
    opportunity: 'Make room for compassion and imagination while keeping one practical reference point.',
  },
}

export function getSignGuidance(sign: ZodiacName): SignGuidance {
  return SIGN_GUIDANCE[sign]
}
