import type { ZodiacName } from '../types'
import type { SignGuidance } from './types'

export const SIGN_GUIDANCE: Record<ZodiacName, SignGuidance> = {
  Aries: {
    id: 'guidance.sign.aries',
    category: 'sign',
    sign: 'Aries',
    tone: 'intensifying',
    intensity: 'high',
    tags: ['action', 'confidence', 'focus', 'boundaries'],
    atmosphere: 'Direct, active, and ready to move.',
    constructive: 'Choose a clear first step and leave room to adjust.',
    watchFor: 'Urgency may become impatience or a reaction before reflection.',
    opportunity: 'Use courage to begin something that has needed momentum.',
  },
  Taurus: {
    id: 'guidance.sign.taurus',
    category: 'sign',
    sign: 'Taurus',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['grounding', 'security', 'resources', 'values', 'rest'],
    atmosphere: 'Steady, sensory, and oriented toward what is sustainable.',
    constructive: 'Slow down enough to notice what genuinely supports stability.',
    watchFor: 'Comfort may become resistance when a small change would help.',
    opportunity: 'Strengthen one resource, routine, or value through consistent care.',
  },
  Gemini: {
    id: 'guidance.sign.gemini',
    category: 'sign',
    sign: 'Gemini',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['communication', 'learning', 'decisions', 'awareness'],
    atmosphere: 'Curious, quick-moving, and open to more than one perspective.',
    constructive: 'Ask a useful question and organize the answer before moving on.',
    watchFor: 'Too many inputs may scatter attention or keep a choice unresolved.',
    opportunity: 'Connect ideas, people, or information that have remained separate.',
  },
  Cancer: {
    id: 'guidance.sign.cancer',
    category: 'sign',
    sign: 'Cancer',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['emotions', 'home', 'security', 'compassion', 'boundaries'],
    atmosphere: 'Sensitive, protective, and attentive to belonging.',
    constructive: 'Acknowledge the feeling and support the need beneath it.',
    watchFor: 'Self-protection may become withdrawal or taking everything personally.',
    opportunity: 'Create a little more safety through care, honesty, or a clear boundary.',
  },
  Leo: {
    id: 'guidance.sign.leo',
    category: 'sign',
    sign: 'Leo',
    tone: 'supportive',
    intensity: 'high',
    tags: ['confidence', 'creativity', 'identity', 'gratitude'],
    atmosphere: 'Expressive, warm, and ready to be seen.',
    constructive: 'Share what is sincere rather than performing for a response.',
    watchFor: 'Pride or the need for recognition may make feedback harder to hear.',
    opportunity: 'Lead with generosity and give a creative idea visible form.',
  },
  Virgo: {
    id: 'guidance.sign.virgo',
    category: 'sign',
    sign: 'Virgo',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['focus', 'routines', 'work', 'awareness', 'structure'],
    atmosphere: 'Observant, practical, and ready to refine what is not working.',
    constructive: 'Improve one useful detail while accepting that progress can be imperfect.',
    watchFor: 'Discernment may turn into overanalysis or unnecessary self-criticism.',
    opportunity: 'Simplify a process, routine, or decision so it serves its purpose better.',
  },
  Libra: {
    id: 'guidance.sign.libra',
    category: 'sign',
    sign: 'Libra',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['relationships', 'values', 'communication', 'boundaries'],
    atmosphere: 'Relational, balancing, and aware of different needs.',
    constructive: 'Seek fairness while including your own preference in the conversation.',
    watchFor: 'Avoiding discomfort may postpone a decision or honest boundary.',
    opportunity: 'Create clearer cooperation through a balanced and direct exchange.',
  },
  Scorpio: {
    id: 'guidance.sign.scorpio',
    category: 'sign',
    sign: 'Scorpio',
    tone: 'intensifying',
    intensity: 'high',
    tags: ['emotions', 'power', 'boundaries', 'transformation', 'awareness'],
    atmosphere: 'Focused, private, and drawn toward what lies beneath the surface.',
    constructive: 'Name the deeper concern without trying to control every outcome.',
    watchFor: 'Suspicion or all-or-nothing thinking may amplify an uncertain situation.',
    opportunity: 'Release one stale pattern and choose a more honest form of engagement.',
  },
  Sagittarius: {
    id: 'guidance.sign.sagittarius',
    category: 'sign',
    sign: 'Sagittarius',
    tone: 'supportive',
    intensity: 'medium',
    tags: ['growth', 'learning', 'perspective', 'beliefs', 'freedom'],
    atmosphere: 'Expansive, candid, and interested in the wider meaning.',
    constructive: 'Explore the larger possibility while staying present with the details.',
    watchFor: 'Optimism or certainty may skip over nuance, limits, or another perspective.',
    opportunity: 'Learn, teach, or take a step that broadens your understanding.',
  },
  Capricorn: {
    id: 'guidance.sign.capricorn',
    category: 'sign',
    sign: 'Capricorn',
    tone: 'challenging',
    intensity: 'high',
    tags: ['responsibility', 'structure', 'work', 'focus', 'boundaries'],
    atmosphere: 'Purposeful, restrained, and focused on durable results.',
    constructive: 'Set a realistic standard and work the next step without rushing.',
    watchFor: 'Responsibility may harden into pessimism, control, or carrying too much alone.',
    opportunity: 'Build useful structure around a goal that matters over time.',
  },
  Aquarius: {
    id: 'guidance.sign.aquarius',
    category: 'sign',
    sign: 'Aquarius',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['change', 'community', 'freedom', 'perspective', 'awareness'],
    atmosphere: 'Independent, future-oriented, and open to an unconventional view.',
    constructive: 'Experiment with a new approach while staying connected to real needs.',
    watchFor: 'Distance or contrarian thinking may replace emotional presence.',
    opportunity: 'Improve a system or contribute an original idea to a shared problem.',
  },
  Pisces: {
    id: 'guidance.sign.pisces',
    category: 'sign',
    sign: 'Pisces',
    tone: 'integrative',
    intensity: 'medium',
    tags: ['imagination', 'compassion', 'creativity', 'rest', 'grounding'],
    atmosphere: 'Receptive, imaginative, and sensitive to subtle impressions.',
    constructive: 'Give intuition a grounded form through rest, art, or one clear action.',
    watchFor: 'Blurred boundaries or wishful thinking may make priorities harder to read.',
    opportunity: 'Use compassion and imagination without abandoning practical clarity.',
  },
}

export function getSignGuidance(sign: ZodiacName): SignGuidance {
  return SIGN_GUIDANCE[sign]
}
